name: Publish Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image with commit SHA
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker build -t ghcr.io/${{ github.repository }}:${COMMIT_SHA} -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Docker image with commit SHA
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker push ghcr.io/${{ github.repository }}:${COMMIT_SHA}
        docker push ghcr.io/${{ github.repository }}:latest

    - name: Log out from Docker Hub
      run: docker logout
